import { seedTemplates } from "@/templates/nextjs/next.template";
import fs from "fs/promises";
import path from "path";

const WORKSPACE_DIR = path.resolve(
  process.cwd(),
  "workspace"
);

export type GeneratedFile = {
  path: string;
  content: string;
};

/**
 * =========================================================
 * LOCAL DEVELOPMENT
 * =========================================================
 *
 * Creates:
 *
 * workspace/
 *   userId/
 *     projectId/
 *       ...
 *
 * This is only used when running locally.
 */
export async function createProjectWorkspace(
  userId: string,
  projectId: string,
  template: string
): Promise<string> {
  const projectPath = path.resolve(
    WORKSPACE_DIR,
    userId,
    projectId
  );

  console.log(
    "Creating local project workspace:",
    projectPath
  );

  await fs.mkdir(projectPath, {
    recursive: true,
  });

  try {
    if (template === "nextjs") {
      await seedTemplates(projectPath);
    } else {
      throw new Error(
        `Unsupported template: ${template}`
      );
    }

    console.log(
      "Local project workspace created:",
      projectPath
    );

    return projectPath;
  } catch (error) {
    console.error(
      "Failed to create local workspace:",
      error
    );

    await fs.rm(projectPath, {
      recursive: true,
      force: true,
    });

    throw new Error(
      `Failed to initialize workspace: ${
        error instanceof Error
          ? error.message
          : "Unknown error"
      }`
    );
  }
}

/**
 * =========================================================
 * PRODUCTION
 * =========================================================
 *
 * Generates the project completely in memory.
 *
 * Nothing is written to Render's filesystem.
 *
 * The returned files can be passed directly to:
 *
 * uploadProjectFiles(
 *   ownerId,
 *   projectId,
 *   files
 * )
 */
export async function generateProjectFiles(
  template: string
): Promise<GeneratedFile[]> {
  if (template !== "nextjs") {
    throw new Error(
      `Unsupported template: ${template}`
    );
  }

  const files: GeneratedFile[] = [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "nextjs-project",
          version: "1.0.0",
          private: true,

          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint",
          },

          dependencies: {
            next: "15.0.0",
            react: "^19.0.0",
            "react-dom": "^19.0.0",
          },

          devDependencies: {
            typescript: "^5",
            "@types/node": "^20",
            "@types/react": "^19",
            "@types/react-dom": "^19",
          },
        },
        null,
        2
      ),
    },

    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2017",
            lib: [
              "dom",
              "dom.iterable",
              "esnext",
            ],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [
              {
                name: "next",
              },
            ],
            paths: {
              "@/*": ["./*"],
            },
          },

          include: [
            "next-env.d.ts",
            "**/*.ts",
            "**/*.tsx",
            ".next/types/**/*.ts",
          ],

          exclude: [
            "node_modules",
          ],
        },
        null,
        2
      ),
    },

    {
      path: "next-env.d.ts",
      content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
`,
    },

    {
      path: "next.config.ts",
      content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
};

export default nextConfig;
`,
    },

    {
      path: "app/layout.tsx",
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js Project",
  description: "Generated by WenWeaver",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },

    {
      path: "app/page.tsx",
      content: `export default function Home() {
  return (
    <main
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "Arial, sans-serif",
      }}
    >
      <div
        style={{
          textAlign: "center",
        }}
      >
        <h1>Welcome to your Next.js project</h1>

        <p>
          Start building your application.
        </p>
      </div>
    </main>
  );
}
`,
    },

    {
      path: "app/globals.css",
      content: `* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
}

body {
  background: white;
  color: black;
}
`,
    },

    {
      path: ".gitignore",
      content: `node_modules
.next
out
.env
.env.local
.env.*.local
`,
    },

    {
      path: "README.md",
      content: `# Next.js Project

Generated by WenWeaver.

## Getting Started

Install dependencies:

\`\`\`bash
npm install
\`\`\`

Start the development server:

\`\`\`bash
npm run dev
\`\`\`

Open:

http://localhost:3000
`,
    },
  ];

  console.log(
    `Generated ${files.length} project files in memory`
  );

  return files;
}